server {
    listen       80;
    server_name  _;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.html;

        try_files $uri $uri/ /index.html;
    }


    location /api/ {
        proxy_pass http://${BACKEND_HOST}:${BACKEND_PORT};
    }

    location ~ /\. {
            deny all;
            access_log off; # 로그도 남기지 마 (지저분하니까)
            log_not_found off;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}
