server {
    listen       80;
    server_name  _;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.html;

        try_files $uri $uri/ /index.html;
    }


    location /api/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 백엔드 서버로 요청을 전달
        proxy_pass http://${BACKEND_HOST}:${BACKEND_PORT};
    }

    location ~ /\. {
            deny all;
            access_log off; # 로그도 남기지 마 (지저분하니까)
            log_not_found off;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}
