version: '3.8'
services:
  leafy-postgres:
    build: ./leafy-postgresql
    image: leafy-postgres:5.0.0-compose
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=${DATASOURCE_URL}
    volumes:
      - leafy_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATASOURCE_URL}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  leafy-backend:
    build: ./leafy-backend
    image: leafy-backend:5.0.0-compose
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://leafy-postgres:5432/${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - leafy-postgres
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure
      
  leafy-front:
    build: ./leafy-frontend
    image: leafy-front:5.0.0-compose
    environment:
      - BACKEND_HOST=leafy-backend
      - BACKEND_PORT=8080
    ports:
      - 80:80
    depends_on:
      - leafy-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: on-failure

volumes:
  leafy_data:
