# Postgresql Database
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DATASOURCE_DB_NAME}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,info
# Cgroup ?? ?? (2025-10-28 ?? ??)
management.metrics.enable.system.cpu.usage=false
management.metrics.enable.process.cpu.usage=false


discord.500.webhook-uri=${DISCORD_500_WEBHOOK_URI}
discord.400.webhook-uri=${DISCORD_400_WEBHOOK_URI}

spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}
jwt.secret-key=${JWT_SECRET}

