# .github/workflows/initial-setup.yml
name: Initial EC2 Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # --- 1. Docker 및 Docker Compose 설치 ---
            if ! command -v docker &> /dev/null; then
                echo "Installing Docker..."
                sudo apt-get update && sudo apt-get install -y docker.io
                sudo systemctl start docker && sudo systemctl enable docker
                sudo usermod -aG docker ${{ secrets.EC2_USERNAME }}
                sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            fi

            # --- 2. docker-compose.yml 파일 생성 (검증된 버전) ---
            echo "Creating docker-compose.yml..."
            cat << EOF > docker-compose.yml
            version: '3.8'
            services:
              leafy-postgres:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/leafy-postgres:latest
                ports:
                  - "5432:5432"
                environment:
                  - POSTGRES_USER=${{ secrets.DATASOURCE_USERNAME }}
                  - POSTGRES_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}
                  - POSTGRES_DB=${{ secrets.DATASOURCE_URL }}
                volumes:
                  - leafy_data:/var/lib/postgresql/data
                restart: always
                healthcheck:
                  test: ["CMD-SHELL", "pg_isready -U ${{ secrets.DATASOURCE_USERNAME }}"]
                  interval: 5s
                  timeout: 5s
                  retries: 5
              leafy-backend:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/leafy-backend:latest
                restart: on-failure
                environment:
                  - SPRING_DATASOURCE_URL=jdbc:postgresql://leafy-postgres:5432/${{ secrets.DATASOURCE_URL }}
                  - SPRING_DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }}
                  - SPRING_DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}
                  - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
                depends_on:
                  leafy-postgres:
                    condition: service_healthy
              leafy-front:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/leafy-frontend:latest
                restart: on-failure
                ports:
                  - "80:80"
                environment:
                    - BACKEND_HOST=leafy-backend
                    - BACKEND_PORT=8080
                depends_on:
                  - leafy-backend
            volumes:
              leafy_data:
            EOF

            # --- 3. 서비스 시작 ---
            echo "Starting services..."
            sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            sudo docker-compose pull
            sudo docker-compose up -d
            
            echo "Initial setup complete."
