# .github/workflows/leafy-backend-build-and-push.yml

name: Backend CI/CD

on:
  push:
    branches:
      - '08-cicd'
    paths:
      - 'leafy-backend/**'
      - '.github/workflows/leafy-backend-build-and-push.yml'

jobs:
  # --- 1. 빌드 및 푸시 Job ---
  build:
    runs-on: ubuntu-latest
    outputs:
      sha_tag: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get short commit sha
        id: get_sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./leafy-backend
          file: ./leafy-backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/leafy-backend:${{ steps.get_sha.outputs.sha }}
          platforms: linux/amd64,linux/arm64

  # --- 2. 배포 Job ---
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            export IMAGE_TAG=${{ needs.build.outputs.sha_tag }}
            export IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/leafy-backend:$IMAGE_TAG
            echo "Deploying image: $IMAGE_NAME"
            
            if [ ! -f docker-compose.yml ]; then
              echo "Creating initial docker-compose.yml"
              cat << EOF > docker-compose.yml
            version: '3.8'
            services:
              leafy-postgres:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/leafy-postgres:latest
                volumes: ["leafy_data:/var/lib/postgresql/data"]
                restart: always
                healthcheck:
                  test: ["CMD-SHELL", "pg_isready -U postgres"]
                  interval: 5s
                  timeout: 5s
                  retries: 5
              leafy-backend:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/leafy-backend:initial
                restart: on-failure
                environment:
                  - SPRING_DATASOURCE_URL=jdbc:postgresql://leafy-postgres:5432/postgres
                  - SPRING_DATASOURCE_USERNAME=postgres
                  - SPRING_DATASOURCE_PASSWORD=postgres
                depends_on:
                  leafy-postgres: { condition: service_healthy }
              leafy-front:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/leafy-frontend:initial
                restart: on-failure
                ports: ["80:80"]
                depends_on: ["leafy-backend"]
            volumes:
              leafy_data:
            EOF
            fi
            
            sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/leafy-backend:.*|image: \$IMAGE_NAME|g" docker-compose.yml
            
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            docker-compose pull leafy-backend
            docker-compose up -d --remove-orphans
            docker image prune -af
