# .github/workflows/leafy-backend-build-and-push.yml

name: Backend CI/CD

on:
  push:
    branches:
      - '08-cicd'
    paths:
      - 'leafy-backend/**'
      - '.github/workflows/leafy-backend-build-and-push.yml'

jobs:
  # --- 1. 빌드 및 푸시 Job ---
  build:
    runs-on: ubuntu-latest
    outputs:
      sha_tag: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get short commit sha
        id: get_sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./leafy-backend
          file: ./leafy-backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/leafy-backend:${{ steps.get_sha.outputs.sha }},${{ secrets.DOCKERHUB_USERNAME }}/leafy-backend:latest
          platforms: linux/amd64

  # --- 2. 배포 Job ---
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # .env 파일에서 백엔드 이미지 태그 라인만 수정 (가장 중요!)
            # 'BACKEND_IMAGE_TAG='로 시작하는 줄을 찾아 새로운 태그로 교체합니다.
            # 파일이 없거나 해당 라인이 없어도 sed가 조용히 넘어갑니다.
            sed -i "s|^BACKEND_IMAGE_TAG=.*|BACKEND_IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/leafy-backend:${{ needs.build.outputs.sha_tag }}|" .env
            
            # 만약 .env 파일에 BACKEND_IMAGE_TAG 라인이 아예 없다면 추가해줍니다. (안정성 강화)
            if ! grep -q "BACKEND_IMAGE_TAG=" .env; then
            echo "BACKEND_IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/leafy-backend:${{ needs.build.outputs.sha_tag }}" >> .env
            fi
          
            echo "Updated .env file with new backend image tag."
            cat .env # 변경된 내용 확인 (디버깅용)
            
            # Docker 로그인
            sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            
            # 백엔드 서비스만 새로 pull 받고 재시작
            sudo docker-compose pull leafy-backend
            sudo docker-compose up -d --no-deps leafy-backend
            
            # 불필요한 이미지 정리
            sudo docker image prune -af
